---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: webservers
  become: true 
  tasks: 

  - name: install apache and php package
    tags: httpd,apache,centos
    yum:
      name: 
      - httpd
      - php
      state: latest
    when: ansible_distribution == "CentOS"
  
  - name: copy default html file for site
    tags: httpd,apache,centos
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644    

- hosts: databaseservers
  become: true
  tasks:
  
  - name: install mariadb package
    yum: 
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: fileservers
  
